export const mySkillsCopy = {
  list: {
    loading: '正在加载我的技能…',
    signInRequired: '登录后才能管理你的技能。',
    title: '我的技能',
    subtitle: '管理你已发布的技能、版本和生命周期。',
    uploadNew: '上传新技能',
    filters: {
      all: '全部',
      active: '正常',
      deleted: '已删除',
      searchPlaceholder: '按 slug 或名称搜索',
    },
    loadFailed: '加载你的技能失败。',
    empty: '当前筛选条件下没有技能。',
    currentVersion: '当前版本',
    updatedAt: '更新时间',
    actions: {
      manage: '管理',
      newVersion: '发布新版本',
      view: '查看',
      restore: '恢复',
      delete: '删除',
    },
  },
  detail: {
    loadingPage: '正在加载技能管理页…',
    signInRequired: '登录后才能管理你的技能。',
    loadingSkill: '正在加载技能…',
    unavailable: '技能管理数据不可用。',
    statusPrefix: '状态',
    uploadNewVersion: '上传新版本',
    viewPublicPage: '查看公开页面',
    currentVersion: '当前版本',
    updatedAt: '更新时间',
    restoreSkill: '恢复技能',
    deleteSkill: '删除技能',
    versions: '版本',
    noVersions: '暂无版本记录。',
    currentTag: '当前',
    downloadZip: '下载 ZIP',
  },
} as const
