export const settingsCopy = {
  loading: '正在加载设置…',
  signInRequired: '登录后才能访问设置。',
  fallbackIdentity: '个人资料',
  title: '设置',
  profile: {
    title: '个人资料设置',
    subtitle: '资料编辑功能将在后续版本提供。',
    uidLabel: 'UID',
    statusLabel: '账号状态',
  },
  bindings: {
    title: '账号绑定',
    subtitle: '',
    feishuTitle: '飞书账号',
    feishuBound: '已绑定飞书账号',
    feishuUnbound: '尚未绑定飞书账号',
    feishuEmailLabel: '飞书同步邮箱',
    feishuEmailMissing: '当前飞书账号未同步邮箱',
    feishuAction: '绑定飞书',
    feishuBinding: '正在拉起飞书授权…',
    feishuHint: '飞书客户端内优先走免登绑定，普通浏览器内会跳转飞书 OAuth 完成绑定。',
    emailTitle: '邮箱',
    emailBound: '已绑定邮箱',
    emailPending: '待验证邮箱',
    emailUnbound: '尚未绑定邮箱',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '设置邮箱密码',
    codePlaceholder: '输入 6 位验证码',
    startBind: '发送验证码',
    binding: '正在发送…',
    verify: '完成绑定',
    verifying: '正在验证…',
    resend: '重新发送',
    bindSuccess: '邮箱验证码已发送，请检查邮箱。',
    verifySuccess: '邮箱绑定完成。',
  },
  tokens: {
    title: 'API Token',
    subtitle: '用于 CLI 和程序化访问的令牌。',
    createdBanner: 'Token 已创建，请立即复制，之后将不会再次展示：',
    dismiss: '关闭',
    labelPlaceholder: 'Token 标签（例如 my-laptop）',
    create: '创建',
    empty: '还没有 Token。',
    createdAt: '创建于',
    lastUsedAt: '最近使用',
    revoke: '撤销',
  },
} as const
