import { getSkillsBrandName } from '../lib/brand'

export const skillsCopy = {
  browse: {
    title: '技能',
    loading: '正在加载技能…',
    subtitleBase: '浏览技能库',
    searchPlaceholder: '按名称、slug 或简介筛选…',
    filters: {
      highlighted: '仅看精选',
      hideSuspicious: '隐藏可疑项',
    },
    sort: {
      ariaLabel: '技能排序',
      relevance: '相关性',
      newest: '最新发布',
      updated: '最近更新',
      downloads: '下载量',
      installs: '安装量',
      stars: '收藏量',
      name: '名称',
      direction: {
        asc: '升序',
        desc: '降序',
      },
    },
    view: {
      list: '列表',
      cards: '卡片',
    },
    empty: '没有符合当前筛选条件的技能。',
    cardSummaryFallback: '一个适合 Agent 的技能包。',
    listSummaryFallback: '暂无简介。',
    pluginBundle: 'Nix 插件包',
    loadMore: '加载更多',
    loadingMore: '正在加载更多…',
    scrollToLoadMore: '滚动以加载更多',
    activeFilters: {
      highlighted: '精选',
      nonSuspicious: '已隐藏可疑项',
    },
  },
  detail: {
    loadingSkill: '正在加载技能…',
    notFound: '未找到该技能。',
    pendingScanTitle: '安全扫描进行中',
    pendingScanBody:
      '你的技能正在接受 VirusTotal 扫描。扫描完成后才会对其他用户可见，通常最多需要 5 分钟。',
    maliciousTitle: '技能已拦截，检测到恶意内容',
    maliciousBody: `${getSkillsBrandName()} 安全系统将该技能判定为恶意内容，已禁用下载。请查看下方扫描结果。`,
    suspiciousTitle: '技能已标记，检测到可疑模式',
    suspiciousBody: `${getSkillsBrandName()} 安全系统将该技能标记为可疑，请在使用前仔细查看扫描结果。`,
    suspiciousAppeal:
      '如果你认为这是误判，请前往 GitHub 提交 issue，我们会解释命中原因以及可采取的处理方式。',
    removedTitle: '技能已被管理员移除',
    removedBody: '该技能已被移除，对其他用户不可见。',
    hiddenTitle: '技能已隐藏',
    hiddenBody: '该技能当前处于隐藏状态，对其他用户不可见。',
    noSummary: '暂无简介。',
    pluginBundleNote: '通过一次 Nix 安装同时打包技能、CLI 二进制和配置要求。',
    cumulativeInstalls: '累计安装',
    duplicateOf: '复制自',
    forkOf: '分叉自',
    basedOn: '基于',
    canonical: '规范来源',
    unstar: '取消收藏技能',
    star: '收藏技能',
    report: '举报',
    manage: '管理',
    scanDisclaimer: '安全需要层层把关，运行前请务必先审查代码。',
    currentVersion: '当前版本',
    downloadZip: '下载 ZIP',
    quickInstall: {
      title: '快捷安装',
      subtitle: '复制命令后可直接在终端安装当前技能。',
      commandTypeAria: '快捷安装命令类型',
      copy: '复制',
      copied: '已复制',
      copyAriaLabel: '复制快捷安装命令',
      copiedAriaLabel: '快捷安装命令已复制',
    },
    installViaNix: '通过 Nix 安装',
    systems: '系统',
    defaultSystem: 'nix-clawdbot',
    configExample: '配置示例',
    configExampleSubtitle: '这个插件包的起始配置如下。',
    pluginBundle: 'Nix 插件包',
    pluginBundleSubtitle: '技能包 · CLI 二进制 · 配置',
    configRequirements: '配置要求',
    requiredEnv: '必需环境变量',
    stateDirs: '状态目录',
    cliHelp: 'CLI 帮助（来自插件）',
    updateTag: '更新标签',
    tagsVersionPrefix: 'v',
    noTags: '暂无标签。',
    tabs: {
      files: '文件',
      compare: '对比',
      versions: '版本',
      loadingFiles: '正在加载文件预览…',
      loadingDiff: '正在加载差异视图…',
    },
    files: {
      readmeTitle: 'SKILL.md',
      readmeFailed: '加载 SKILL.md 失败：',
      totalFiles: '个文件',
      noFiles: '暂无可用文件。',
      selectFile: '选择一个文件',
      selectPrompt: '选择文件后可在这里预览。',
      fileMetadataMissing: '缺少文件元数据。',
      loadFileFailed: '加载文件失败',
      loadFileFailedWithReason: '加载文件失败：',
    },
    versions: {
      title: '版本',
      subtitle: '查看发布历史并下载指定版本。',
      loading: '正在加载版本…',
      empty: '暂无版本记录。',
      current: '当前版本',
      zip: 'ZIP',
    },
    comments: {
      title: '评论',
      subtitle: '分享这个技能的使用心得、注意事项或发布反馈。',
      signInHint: '登录后即可发表评论。',
      bodyRequired: '评论内容不能为空。',
      placeholder: '写下你的评论',
      posting: '正在发布…',
      submit: '发表评论',
      loading: '正在加载评论…',
      empty: '还没有评论。',
      you: '你',
    },
    diff: {
      title: '版本对比',
      subtitle: '比较两个已发布版本之间的文件内容差异。',
      leftVersion: '左侧版本',
      rightVersion: '右侧版本',
      availableFiles: '可对比文件：',
      empty: '没有可对比的文件。',
      leftFallback: '左侧',
      rightFallback: '右侧',
      noFileInVersion: '该版本中没有此文件。',
      failed: '加载差异失败：',
    },
    reportDialog: {
      title: '举报技能',
      subtitle: '请描述问题，方便管理员快速审核。',
      ariaLabel: '举报原因',
      placeholder: '请说明管理员需要了解的情况',
      cancel: '取消',
      submitting: '正在提交…',
      submit: '提交举报',
      reasonRequired: '举报原因不能为空。',
      phase2: '举报功能将在 Phase 2 提供。',
    },
    installCard: {
      runtimeRequirements: '运行要求',
      os: '操作系统',
      bins: '可执行文件',
      anyBin: '任一可执行文件',
      env: '环境',
      config: '配置',
      primaryEnv: '主环境',
      environmentVariables: '环境变量',
      optional: '可选',
      required: '必需',
      dependencies: '依赖',
      source: '源码',
      install: '安装方式',
      links: '链接',
      homepage: '主页',
      repository: '仓库',
      docs: '文档',
    },
    security: {
      title: '安全扫描',
      benign: '安全',
      malicious: '恶意',
      suspicious: '可疑',
      loading: '扫描中…',
      pending: '待扫描',
      error: '异常',
      details: '详情',
      findingsInContext: '扫描发现',
      doNotInstall: '请勿安装此技能',
      suspiciousGuidance: '安装前请重点确认',
      assessment: '综合判断',
      viewReport: '查看报告',
      confidence: '置信度',
      codeInsight: '代码洞察',
    },
  },
  badges: {
    deprecated: '已弃用',
    official: '官方',
    highlighted: '精选',
  },
} as const
