export const soulsCopy = {
  browse: {
    title: '灵魂',
    loading: '正在加载灵魂…',
    countLabel: '{showing}{totalPart} 个灵魂。',
    totalPart: ' / {total}',
    searchPlaceholder: '按名称、slug 或简介筛选…',
    sortAriaLabel: '灵魂排序',
    sortDirectionAria: '灵魂排序：{direction}',
    sort: {
      newest: '最新发布',
      updated: '最近更新',
      downloads: '下载量',
      stars: '收藏量',
      name: '名称',
      asc: '升序',
      desc: '降序',
    },
    view: {
      list: '列表',
      cards: '卡片',
    },
    empty: '没有符合当前筛选条件的灵魂。',
    summaryFallbackCard: '一个 SOUL.md 套件。',
    summaryFallbackList: 'SOUL.md 套件。',
  },
  detail: {
    loading: '正在加载灵魂…',
    notFound: '未找到该灵魂。',
    noSummary: '暂无简介。',
    authorPrefix: '作者',
    star: '收藏灵魂',
    unstar: '取消收藏灵魂',
    currentVersion: '当前版本',
    downloadSoul: '下载 SOUL.md',
    downloadSoulAria: '下载 SOUL.md',
    versions: '版本',
    noVersions: '暂无可用版本。',
    comments: '评论',
    commentPlaceholder: '写点备注…',
    postComment: '发表评论',
    signInToComment: '登录后即可评论。',
    noComments: '还没有评论。',
    currentTag: '当前',
    summaryFallbackReadme: '# SOUL.md\n\n内容将在 Phase 2 提供。',
  },
} as const
