export const uploadCopy = {
  nouns: {
    skill: '技能',
    soul: '灵魂',
  },
  authRequired: '登录后才能上传{type}。',
  title: '发布{type}',
  subtitle: '拖入一个包含 {requiredFile} 和文本文件的文件夹，其余步骤交给我们处理。',
  fields: {
    slug: '标识（slug）',
    displayName: '显示名称',
    version: '版本',
    tags: '标签',
    changelog: '更新日志',
  },
  placeholders: {
    slug: '{type}-name',
    displayName: '我的{type}',
    version: '1.0.0',
    tags: 'latest, stable',
    changelog: '描述这个{type}本次更新了什么…',
  },
  dropzone: {
    title: '拖入文件夹',
    hint: '我们会保留文件夹路径，并自动展开最外层包装目录。',
    chooseFolder: '选择文件夹',
    noFiles: '尚未选择文件。',
    ignoredMacJunk: '已忽略 {count} 个 macOS 垃圾文件（{labels}{suffix}）',
  },
  validation: {
    title: '校验结果',
    allPassed: '所有检查均已通过。',
    fixIssues: '请先修复校验问题后再继续。',
    slugRequired: '标识（slug）不能为空。',
    slugFormat: '标识（slug）只能使用小写字母、数字和短横线。',
    slugTaken: '该标识已被其他用户占用，请更换后再发布。',
    displayNameRequired: '显示名称不能为空。',
    versionInvalid: '版本号必须是合法的 semver（例如 1.0.0）。',
    versionMustIncrease: '当前最新版本为 {version}，请填写更高版本后再发布。',
    tagsRequired: '至少需要一个标签。',
    filesRequired: '请至少添加一个文件。',
    requiredFile: '{requiredFile} 不能为空。',
    removeNonText: '请移除非文本文件：{names}',
    sizeExceeded: '文件总大小不能超过 50MB。',
    perVersionSizeExceeded: '每个版本的总大小不能超过 50MB。',
  },
  status: {
    uploading: '正在上传文件…',
    publishing: '正在发布…',
    checkingSlug: '正在检查标识状态…',
    slugAvailable: '该标识可用于新建技能。',
    slugOwned: '你已发布过该技能，本次将作为新版本发布。',
    slugCheckFailed: '暂时无法确认标识状态，提交时将以后端校验为准。',
    latestVersion: '当前最新版本：{version}',
    changelogReady: '更新日志已就绪（可按需继续编辑）。',
    autofilledFromSkill: '已根据 {requiredFile} 自动填充名称，可继续修改。',
    versionExists: '该版本已存在，请将版本号升级后再发布。',
    ownerConflict: '该标识已被其他用户占用，请更换后再发布。',
    publishFailed: '发布失败，请稍后重试。',
  },
  actions: {
    publish: '发布{type}',
    publishVersion: '发布新版本',
    removeFile: '删除',
  },
} as const
